//
// Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
//
// See LICENSE.txt for license information
//

#ifndef DPU_OFFLOAD_ENVVARS_H
#define DPU_OFFLOAD_ENVVARS_H

#define OFFLOAD_CONFIG_FILE_PATH_ENVVAR "OFFLOAD_CONFIG_FILE_PATH"
#define BLUEFIELD_NODE_NAME_ENVVAR "BLUEFIELD_NODE_NAME"

#endif // DPU_OFFLOAD_ENVVARS_H