//
// Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
//
// See LICENSE.txt for license information
//

#ifndef DPU_OFFLOAD_ENVVARS_H
#define DPU_OFFLOAD_ENVVARS_H

#define OFFLOAD_CONFIG_FILE_PATH_ENVVAR "OFFLOAD_CONFIG_FILE_PATH"
#define BLUEFIELD_NODE_NAME_ENVVAR "BLUEFIELD_NODE_NAME"

#define SERVER_PORT_ENVVAR "DPU_OFFLOAD_SERVER_PORT"
#define SERVER_IP_ADDR_ENVVAR "DPU_OFFLOAD_SERVER_ADDR"

#define INTER_DPU_ADDR_ENVVAR "INTER_DPU_CONN_ADDR"
#define INTER_DPU_PORT_ENVVAR "INTER_DPU_CONN_PORT"

#define LIST_DPUS_ENVVAR "DPU_OFFLOAD_LIST_DPUS"

#define DPU_OFFLOAD_DBG_VERBOSE "DPU_OFFLOAD_DBG_VERBOSE"

#endif // DPU_OFFLOAD_ENVVARS_H